### PR TITLE
Mongo 2.6ssl 3.3

### PR DESCRIPTION
**Pull request by krallin**
Replaces: #10, #11 
Fixes: #1, #8

### CODE REVIEW

**Comment by krallin** [comment]
@fancyremarker as discussed, this includes a new script to parse URLs. Do note that this requires Python, so it adds a little weight to the images. I'm happy to look into whether I can trim that down (I think it might be possible using `python-minimal`).

Cheers,

**Comment by krallin** [comment]
@fancyremarker While we're in here, I think it might be worth adding:

```
set -o errexit
set -o nounset
set -o pipefail
```

In the run DB script. Let me know your thoughts.

Cheers,

**Comment by fancyremarker** [comment]
Hey @krallin , this looks great to me. The `--dump` and `--restore` tests are excellent, thanks.

I forgot where we left this; i.e., whether you wanted to merge now and refactor into DRYer shared and version-specific files later, or whether there were more changes to be made now. But feel free to merge at will.

**Comment by krallin** [comment]
@fancyremarker I'm actually just wrapping this up (making the `-o` changes I mentioned above). 

I'm actually just done; I'm pushing the last commit right now so you can review: https://github.com/krallin/docker-mongodb/commit/aa2f67c5329e7355ef0e7b2d45b7e64d3fb63e6c

One change in behavior: `run-database.sh` will now throw an error if you pass e.g. `--clinet` (i.e. an unrecognized option) instead of launching Mongod. I think that's preferable behavior, but let me know your thoughts.

Cheers,

**Comment by fancyremarker** [comment]
Changing the behavior to throw an error on unrecognized options is :+1: .

**Comment by krallin** [comment]
Sounds good; feel free to merge if reviewing shows no problems then! :)

**Pull request merged**
